version: "3.8"
services:
  MassTransitSagaDeadlock.Worker:
    image: masstransitsaga/deadlock.worker:linux
    build:
      context: .
      dockerfile: MassTransitSagaDeadlock.Worker/Dockerfile 
    deploy:
      replicas: 2
  MassTransitSagaDeadlock.Console.Client:
    image: masstransitsaga/deadlock.console.client:linux
    build:
      context: .
      dockerfile: MassTransitSagaDeadlock.Console.Client/Dockerfile 
    environment:
      - MESSAGES_COUNT=20
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1401:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P@ssword1!
  rabbit:
    image: rabbitmq:3-management-alpine
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672